### ISSUE TITLE
Update to latest version of croc

### ISSUE THREAD

**Issue by fredrikfoss** [Marksdo/iCroc#2]
Hi, iCroc no longer works with the latest version of croc (v10.0.8 ATM) and at least a few of the other later releases. Error message:

```
problem with decoding: unexpected end of JSON input
```

**Comment by Marksdo** [comment]
Thanks for report this, it need some days to upgrade new version. 

You can downgrade croc to V9.x

**Comment by Marksdo** [comment]
Just mark.

[v10.0.0](https://github.com/schollz/croc/releases/tag/v10.0.0)
v9.6.16 was a breaking change so I have re-released it as v10.0.0 to signal that. clients must be >=v9.6.16 or >=v10 to be compatible.
Full Changelog: https://github.com/schollz/croc/compare/v9.6.17...v10.0.0

**Comment by Marksdo** [comment]
The new version (V1.2) can now be updated in the app store.
